//ADDIGP
//BBC
//BBS
//BEQC
//BNEC
//BFOS
//BFOZ
//LEA_H
//LEA_W
//LEA_D
//LEA_B_ZE
//LEA_H_ZE
//LEA_W_ZE
//LEA_D_ZE
//LBGP
//LBUGP
//LHGP
//LHUGP
//LWGP
//LWUGP
//LDGP
//SBGP
//SHGP 
//SWGP 
//SDGP
//FFB
//FFZMISM
//FFMISM 
//FLMISM

//EX9_IT 
//EXEC_IT 

//VLN8_V
//VLNU8_V
//FCVT_S_BF16
//FCVT_BF16_S
//VFWCVT_S_BF16
//VFNCVT_BF16_S

//FLHW
//FSHW          


// BRANCH instructions
// BFOS Rd, Rs1,  #msb[5:0], #lsb[5:0]    (for  RV64)
`DEFINE_V5_INSTR(BBC  ,    B_FORMAT, BRANCH, RV64V5) // BBC Rs1,  #cimm[5:0], #imm[10:1]    (for RV64)
`DEFINE_V5_INSTR(BBS  ,    B_FORMAT, BRANCH, RV64V5) // BBS Rs1,  #cimm[5:0], #imm[10:1]    (for RV64)

`DEFINE_V5_INSTR(BEQC ,    B_FORMAT, BRANCH, RV64V5) //   BEQC Rs1,  #cimm[6:0], #imm[10:1]
`DEFINE_V5_INSTR(BNEC ,    B_FORMAT, BRANCH, RV64V5) //   BNEC Rs1,  #cimm[6:0], #imm[10:1]
`DEFINE_V5_INSTR(BFOS ,    B_FORMAT, BRANCH, RV64V5) //   BFOS Rd, Rs1,  #msb[5:0], #lsb[5:0]    (for  RV64)
`DEFINE_V5_INSTR(BFOZ ,    B_FORMAT, BRANCH, RV64V5) //   BFOZ Rd, Rs1,  #msb[5:0], #lsb[5:0]    (for  RV64)
// ARITHMETIC intructions
`DEFINE_V5_INSTR(ADDIGP,    I_FORMAT, ARITHMETIC, RV64V5) //18 bits imm

`DEFINE_V5_INSTR(LEA_H    ,    R_FORMAT, ARITHMETIC, RV64V5) //  LEA_*_*  Rd, Rs1, Rs2 
`DEFINE_V5_INSTR(LEA_W    ,    R_FORMAT, ARITHMETIC, RV64V5) 
`DEFINE_V5_INSTR(LEA_D    ,    R_FORMAT, ARITHMETIC, RV64V5) 
`DEFINE_V5_INSTR(LEA_B_ZE ,    R_FORMAT, ARITHMETIC, RV64V5) 
`DEFINE_V5_INSTR(LEA_H_ZE ,    R_FORMAT, ARITHMETIC, RV64V5) 
`DEFINE_V5_INSTR(LEA_W_ZE ,    R_FORMAT, ARITHMETIC, RV64V5) 
`DEFINE_V5_INSTR(LEA_D_ZE ,    R_FORMAT, ARITHMETIC, RV64V5) 
// LOAD instructions format - instr rd,[+imm[17:0]]
`DEFINE_V5_INSTR(LBGP ,     I_FORMAT, LOAD, RV64V5) 		
`DEFINE_V5_INSTR(LBUGP,     I_FORMAT, LOAD, RV64V5)
`DEFINE_V5_INSTR(LHGP ,     I_FORMAT, LOAD, RV64V5)
`DEFINE_V5_INSTR(LHUGP,     I_FORMAT, LOAD, RV64V5)
`DEFINE_V5_INSTR(LWGP ,     I_FORMAT, LOAD, RV64V5)
`DEFINE_V5_INSTR(LWUGP,     I_FORMAT, LOAD, RV64V5)
`DEFINE_V5_INSTR(LDGP ,     I_FORMAT, LOAD, RV64V5)

// STORE instructions format - instr rd,[+imm[17:0]]
`DEFINE_V5_INSTR(SBGP ,     S_FORMAT, STORE, RV64V5)
`DEFINE_V5_INSTR(SHGP ,     S_FORMAT, STORE, RV64V5)
`DEFINE_V5_INSTR(SWGP ,     S_FORMAT, STORE, RV64V5)
`DEFINE_V5_INSTR(SDGP ,     S_FORMAT, STORE, RV64V5)

// instr rd,rs1,rs2
`DEFINE_V5_INSTR(FFB        ,    R_FORMAT, ARITHMETIC, RV64V5) 
`DEFINE_V5_INSTR(FFZMISM    ,    R_FORMAT, ARITHMETIC, RV64V5) 
`DEFINE_V5_INSTR(FFMISM     ,    R_FORMAT, ARITHMETIC, RV64V5) 
`DEFINE_V5_INSTR(FLMISM     ,    R_FORMAT, ARITHMETIC, RV64V5) 

// EXEC.IT (Execution on Instruction Table) format - instr imm[11:2]
//   EXEC.IT imm[11:2]
//   EX9.IT  imm[10:2] (Alias to EXEC.IT 0~511, imm[11]==0)
//`DEFINE_V5_INSTR(EX9_IT  ,     I_FORMAT, ARITHMETIC, RV64V5, UIMM) 		
//`DEFINE_V5_INSTR(EXEC_IT ,     I_FORMAT, ARITHMETIC, RV64V5, UIMM) 		
// Floatin  point half-precision - format - instr frs2, imm[11:0](rs1)
`DEFINE_V5_INSTR(FLHW  ,     I_FORMAT, LOAD, RV64V5) 		
`DEFINE_V5_INSTR(FSHW  ,     S_FORMAT, STORE, RV64V5) 		

`DEFINE_VA_INSTR(VLN8_V       ,     VA_FORMAT, ARITHMETIC, RV64ZVBB, {VV, VX})
`DEFINE_VA_INSTR(VLNU8_V      ,     VA_FORMAT, ARITHMETIC, RV64ZVBB, {VV, VX})
`DEFINE_VA_INSTR(FCVT_S_BF16  ,     VA_FORMAT, ARITHMETIC, RV64ZVBB, {VV, VX})
`DEFINE_VA_INSTR(FCVT_BF16_S  ,     VA_FORMAT, ARITHMETIC, RV64ZVBB, {VV, VX})
`DEFINE_VA_INSTR(VFWCVT_S_BF16,     VA_FORMAT, ARITHMETIC, RV64ZVBB, {VV, VX})
`DEFINE_VA_INSTR(VFNCVT_BF16_S,     VA_FORMAT, ARITHMETIC, RV64ZVBB, {VV, VX})


